### ISSUE TITLE
Did find class"com.alibaba.wukong.im.message.Messagelmpl"

### ISSUE THREAD

**Issue by pkz0313** [veryyoung/DingDingLuckyMoney#15]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.wukong.im.message.MessageImpl" on path: DexPathList[[zip file "/data/app/com.alibaba.android.rimet-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.alibaba.android.rimet-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more
java.lang.NullPointerException

什么问题呢

**Comment by veryyoung** [comment]
@pkz0313 钉钉第一次启动会这样，后面就好了
